### ISSUE TITLE
automatic layout adaptation is lost

### ISSUE THREAD

**Issue by TeresaM12** [ambrt/joplin-plugin-referencing-notes#4]
The plugin itself works very nice. Thanks! I like the option to insert the backlinks also manually.

First I would like to mention that this plugin is not the only one with this "problem", but it is the only one were I do not  understand the source of the problem.

**Without the plugin:**
- the width of the side bar and the note bar is fixed (not visible in the examples)
- when I adapt the joplin app window size, the editor and preview window take up all the rest of the window (also when only one of them is active) and line wrap is active so that no horizontal scrolling is needed
- looks like this (there is also a scrollbar for vertical scrolling)
![image](https://user-images.githubusercontent.com/37457901/107850976-b4f8de80-6e06-11eb-9540-fc5065f928cc.png) 

**With the plugin:**
- the width of the side bar and the note bar is fixed
- when I adapt the joplin app window size the size of the editor and/or preview pane is fixed, either when enlarging or when making it (joplin window) smaller at a certain size even in both resizing directions
- there exists an additional empty right hand pane 
- This 
![image](https://user-images.githubusercontent.com/37457901/107850894-22f0d600-6e06-11eb-9629-bf6787b71594.png)
is a joplin window with only preview active and I just enlarged the joplin window but the preview pane does not adapt its size only the empty right hand pane gets wider.
- What I like even less when I make it smaller in the horizontal direction, I can not see everything anymore (no scrollbar available)
![image](https://user-images.githubusercontent.com/37457901/107850908-4b78d000-6e06-11eb-98d8-a4e9fb4671fb.png)

**System**
The plugins which seem not to have this problem do not display any icons and also no further information in an additional pane.
Backlinks v 2.0.5 (probably older versions as well)
The screen shots are from a mac (running MacOS 10.15)  
Joplin 1.7.10 (prod, darwin)
Revision: fb1c876 (master)
and
Joplin 1.7.11 (prod, darwin)
Revision: f560563 (master)

But I have the same problem running Joplin 1.7.6 - 1.7.11 on a Win10 device.

**Comment by ambrt** [comment]
HI Teresa, 

I reproduced this error on my machine.
These are actually two bugs.

It seems that its something with Joplin keeping panels info (width)
even when those panels aren't created like after restart of this plugin.
And, resizing of editor and preview isn't called.

I will report it to main Joplin repo b/c i don't see anything that i can do 
on my side.
Thanks for reporting.

**Comment by TeresaM12** [comment]
Thanks for checking and passing it on.

**Comment by TeresaM12** [comment]
Did you change something else in the 2.0.9 release? I can not reproduce the "ghost" panel and resizing issue anymore (which is very good unfortunately your plugin was not the only potential trigger ...). Joplin version is still the same.

**Comment by ambrt** [comment]
@TeresaM12  version 2.0.9 have different way of dealing with panel - instead of hiding it when turned off it doesn't create it (at least should not create it).
This requires to full restart to see effect as opposed to switching it via menu setting, like it was in prev version.
