### ISSUE TITLE
No joplin icon in preview pane for automatic backlinks

### ISSUE THREAD

**Issue by Petemir** [ambrt/joplin-plugin-referencing-notes#8]
Hello,

Thank you for your plugin, it's an invaluable addition for a zettelkasten-like workflow in Joplin :). 

One thing I have noticed is that usually links that are internal to Joplin show a preceding icon that lets you know that the link won't make you leave the app. This icon appears if I generate the backlinks manually by clicking on the toolbar plugin icon (hand pointing to the left), but the icon doesn't appear in the automatically generated backlinks.

<img width="427" alt="image" src="https://user-images.githubusercontent.com/287105/126800227-ac96d44e-29de-4273-a237-59659ac3e7c7.png">

I am not sure if it is a bug, or it could be considered a feature, but I believe it would be important to include the link so it is consistent with the rest of joplin.

Thanks!

**Comment by ambrt** [comment]
Hi

New version version have option to include icon (by defaults its off)
Thanks for posting an issue. It will be published soon.
